name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  transparent_image: ^0.1.0
  flutter_webview_plugin: "^0.3.10+1"
  webview_flutter: 0.3.24
  shared_preferences: "^0.4.1"
  event_bus: "^1.0.1"
  http: '>=0.11.3+12'
  flutter_gifimage: ^1.0.0
  simple_animations: 1.3.4
  flutter_swiper: ^1.1.6
  flare_flutter: ^1.8.3
  pull_to_refresh: ^1.5.7
  pull_to_refresh_notification: 0.3.5
  flutter_easyrefresh: ^2.1.1
  masonry_grid: 0.3.1+2
  waterfall_flow: any
  flutter_cupertino_date_picker_fork: ^1.0.1
#  qrscan: ^0.2.17
#  flutter_plugin_qrcode: ^1.0.1
  permission_handler: 5.0.1+1
  keyboard_avoider: 0.1.2
  image_picker: 0.6.7+21
  video_player: 0.11.0
  syncfusion_flutter_charts: 18.4.35
  flutter_barrage: 0.4.6
  pimp_my_button: 1.0.0
  #  custom_refresh_plugin:
#    #git 方式依赖
#    git:
#      #仓库地址
#      url: https://github.com/zhaolongs/flutter_custom_refresh_plugin.git
#      # 分支
#      ref: master
#  fluttertoast: ^3.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
#  assets:
#    - images/img.png
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/image/
     - file/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: aliIcon
       fonts:
         - asset: fonts/iconfont.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
#  fonts:
#    - family: aliIcon
#    fonts:
#      - asset: fonts/iconfont.ttf